Diagram based Database
EddyShimwa/vet_clinic_db pull request #7
Opened 2023-02-28 14:50 UTC by EddyShimwa

### At this step we create a database based on diagram! And we have been to:
- Create table tables like patients, invoices, invoice_items, medical_histories,  and treatments!

### The figure bellow shows how the database schema looks

![pair_programming_schema](https://user-images.githubusercontent.com/88631022/221889349-19ff375c-0f06-4303-8a3a-94d216ef8ac2.png)

2023-02-28 15:23 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @EddyShimwa and @Kashif-Saleem-Ghuman,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-28 15:23 UTC, Omar-Muhamad commented on schema_based_on_diagram.sql
> +    NOT VALID;
- [ ] Please create a new table `medical_histories_treatments` to address the many-to-many relationship between `medical_histories` and `treatments` tables and add the foreign keys in it:
```sql
 CREATE TABLE medical_histories_treatments (
    medical_history_id int references medical_histories(id),
    treatment_id int references treatments(id),
  );
```

2023-02-28 15:23 UTC, Omar-Muhamad commented on schema_based_on_diagram.sql
> +
- [ ] Kindly make sure that all FOREIGN KEYS have indexes created

2023-02-28 16:38 UTC, Kashif-Saleem-Ghuman commented
@Omar-Muhamad  Thank you for reviewing our PR and providing valuable feedback

2023-02-28 17:26 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @Kashif-Saleem-Ghuman and @EddyShimwa     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 20:37 UTC, EddyShimwa commented
Thanks @hiromataba for reviewing this PR!!

2023-02-28 20:38 UTC, merged

2023-03-01 06:41 UTC, Kashif-Saleem-Ghuman commented
@hiromataba  Thank you for approving our PR :)